/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app.buyer;

import java.awt.Point;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Samuel
 */
public class BuyerGui extends javax.swing.JFrame {

    private BuyerAgent agent;

    /**
     * Creates new form BuyerGui
     */
    public BuyerGui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Comprador");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Comprador");

        setResizable(false);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] {
                "Estado", "Libro", "Precio actual", "Máximo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                onRowClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void onRowClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onRowClicked
        JTable table = (JTable) evt.getSource();
        DefaultTableModel tableModel = (DefaultTableModel) table.getModel();
        Point p = evt.getPoint();
        int row = table.rowAtPoint(p);
        
        if(evt.getClickCount() == 2) {
            if(tableModel.getValueAt(row, 0).equals("No en puja")) {
                String result = (String) JOptionPane.showInputDialog(this, "Introduzca el precio máximo que está dispuesto a pagar", "Pujar",
                        JOptionPane.QUESTION_MESSAGE, null, null, null);

                if(result != null && result.length() > 0) {
                    tableModel.setValueAt("En puja", row, 0);
                    tableModel.setValueAt(Float.valueOf(result), row, 3);
                    this.agent.bidForBook((String) tableModel.getValueAt(row, 1), Float.valueOf(result));
                }
            } else {
                String book = (String) tableModel.getValueAt(row, 1);
                int confirm = JOptionPane.showConfirmDialog(this, "Estás seguro de que deseas abandonar la puja para " + book,
                        "Abandonar la puja", JOptionPane.YES_NO_OPTION);

                if(confirm == JOptionPane.YES_OPTION) {
                    this.agent.deregisterBook(book);
                }
            }
        }
    }//GEN-LAST:event_onRowClicked

    public static BuyerGui start() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuyerGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuyerGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuyerGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuyerGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        return new BuyerGui();
    }
    
    public BuyerGui setAgent(BuyerAgent agent) {
        this.agent = agent;
        return this;
    }

    public void addBook(String book) {
        DefaultTableModel model = (DefaultTableModel) this.jTable1.getModel();
        model.addRow(new Object[]{"No en puja", book, null, null});
    }

    public void updatePrice(String book, float newPrice) {
        DefaultTableModel model = (DefaultTableModel) this.jTable1.getModel();

        for(int i = 0; i < model.getRowCount(); i++) {
            if(model.getValueAt(i, 1).equals(book)) {
                model.setValueAt(newPrice, i, 2);
                break;
            }
        }
    }

    // TODO: do not delete
    public void bookPriceExceeded(String book) {
        DefaultTableModel model = (DefaultTableModel) this.jTable1.getModel();

        for(int i = 0; i < model.getRowCount(); i++) {
            if(model.getValueAt(i, 1).equals(book)) {
                model.removeRow(i);
                break;
            }
        }

        JOptionPane.showMessageDialog(this, String.format("El libro %s ha excedido tu precio máximo", book));
    }

    // TODO: do not delete
    public void bookWon(String book) {
        DefaultTableModel model = (DefaultTableModel) this.jTable1.getModel();

        for(int i = 0; i < model.getRowCount(); i++) {
            if(model.getValueAt(i, 1).equals(book)) {
                model.removeRow(i);
                break;
            }
        }

        JOptionPane.showMessageDialog(this, String.format("Enhorabuena, has conseguido el libro %s", book));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
